# Generated by Django 4.2.4 on 2023-08-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("melsite2", "0004_candidate_delete_predrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("complete", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="FreqList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_val", models.CharField(max_length=300)),
                ("freq_val", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="Candidate",
        ),
        migrations.AddField(
            model_name="city",
            name="cityname",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="melsite2.freqlist"
            ),
        ),
    ]
