# Generated by Django 4.2.4 on 2023-08-16 01:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("melsite2", "0006_freqlist_lr_pred_alter_freqlist_freq_val"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freqlist",
            old_name="lr_pred",
            new_name="rf_pred",
        ),
    ]
